let shopItemsData = [
  {
  id:"4631876311",
  name: "Men's Eureka Tee - White",
  price: 35,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-one.jpg"
  },
  {id:"1561373557",
  name: "A8 Trucker Snapback",
  price: 45,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-two.jpg"},
  {id:"7616515867",
  name: "Golden State x CONA STO Pullover",
  price: 85,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-three.jpg"},
  {id:"4603167861",
  name: "Nirvana Throwback Tee",
  price: 30,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-four.jpg"},
  {id:"9141346734",
  name: "Smiley Throwback Tee",
  price: 30,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-five.jpg"},
  {id:"4739471054",
  name: "Yasiel Puig Official MLB Jersey",
  price: 110,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-six.jpg"},
  {id:"5506460791",
  name: "NYC Oversized Puffer Jacket",
  price: 105,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-seven.jpg"},
  {id:"1079163452",
  name: "Ripped Raw Denim Faded Jeans",
  price: 90,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-eight.jpg"},
  {id:"4998710064",
  name: "Levi's Faded Denim 511 Jeans",
  price: 55,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-nine.jpg"},
  {id:"1765151483",
  name: "DBZ Goku x CONA STO Graphic Tee",
  price: 45,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-ten.jpg"},
  {id:"8510563140",
  name: "FC Clothing Co Branded Tee",
  price: 35,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-eleven.jpg"},
  {id:"3431316557",
  name: "Men's Faded Denim Thrift Jacket",
  price: 80,
  desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
  img: "images/img-twelve.jpg"}
];